IF (NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Address' AND COLUMN_NAME = 'StudentID'))
BEGIN
	ALTER TABLE [dbo].[Address] ADD StudentID NVARCHAR(500) NULL;
END
IF (NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Address' AND COLUMN_NAME = 'UploadStudentID'))
BEGIN
	ALTER TABLE [dbo].[Address] ADD UploadStudentID NVARCHAR(500) NULL;
END
IF (NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Address' AND COLUMN_NAME = 'UploadID'))
BEGIN
	ALTER TABLE [dbo].[Address] ADD UploadID NVARCHAR(500) NULL;
END
IF (NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Address' AND COLUMN_NAME = 'BuildingNo'))
BEGIN
	ALTER TABLE [dbo].[Address] ADD BuildingNo NVARCHAR(500) NULL;
END